package COOL.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class Attribute_BehaviorDescriptor extends BaseAttribute_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public Attribute_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "COOL.structure.Attribute";
  }
}
