package COOL.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class BaseAttribute_BehaviorDescriptor extends IFeature_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public BaseAttribute_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "COOL.structure.BaseAttribute";
  }
}
